version: 2

project_name: anpan

before:
  hooks:
    - go mod tidy

builds:
  - id: anpan
    main: .
    binary: anpan
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/KabosuNeko/anpan/cmd.Version={{ .Version }}

archives:
  - id: default
    builds:
      - anpan
    name_template: "anpan-{{ .Os }}-{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - assets/*

checksum:
  name_template: "sha256sums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
